model:
    nb_samp: 64600
    first_conv: 1024
    in_channels: 1
    filts: [20, [20, 20], [20, 128], [128, 128]]
    blocks: [2, 4]
    nb_fc_node: 1024
    gru_node: 1024
    nb_gru_layer: 3
    nb_classes: 2
